spring:
  application:
    name: Cerebral
  datasource:
    url: jdbc:mysql://localhost:3306/deepseek_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    openai:
      base-url: https://api.deepseek.com # DeepSeek的OpenAI式端点
      api-key: your api key # DeepSeek的OpenAI式API Key
      chat:
        options:
          model: 'deepseek-reasoner' # 个人可以选择，此处时deepseek-R1模型